### ISSUE TITLE
customPaging not working

### ISSUE THREAD

**Issue by cmartin6** [heimrichhannot/contao-slick-bundle#47]
**Context**
Contao version: 4.9.16
Bundle version: 1.5.0
PHP version: 7.4

**Description**
I am trying to use a custom paging function (`basic.slickCustomPaging`) for my slick-slider but unfortunately i am getting this error in the js-console: `o.options.customPaging.call is not a function` 
Could this please be fixed?

**Comment by koertho** [comment]
Hi, we're not responsible for the slick library. But I think, you don't call it on the correct instance of slick. Have a look at the js events here: https://github.com/heimrichhannot/contao-slick-bundle/blob/master/docs/developers.md
Otherwise you must provide more information how this is a issue of this bundle.

**Comment by cmartin6** [comment]
This is still not working. If I use `heimrichhannot/contao-slick` it works...
